# -*- coding: utf-8 -*-
"""level_for_and_if.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1F8Sy4ktznBCfMqTi1Jt0qEeO2AZuj6aT
"""

a,b,c = map(int, input().split())
print((a+b)%c)
print(((a%c)+(b%c))%c)
print((a*b)%c)
print(((a%c)*(b%c))%c)

a = int(input().strip())
b = input().strip()

first = a * int(b[-1])
second = a * int(b[1])
third = a * int(b[0])

print(first)
print(second)
print(third)
print(first+second *10+third*100)

a,b,c = map(int, input().split())
print(a+b+c)

print('\\    /\\')
print(' )  ( \')')
print('(  /  )')
print(' \\(__)|')

print('|\\_/|')
print('|q p|   /}')
print('( 0 )"""\\')
print('|"^"`    |')
print('||_/=\\\\__|')

a, b = map(int, input().split())
if a>b:
  print('>')
elif a<b:
  print('<')
else:
  print('==')

h, m = map(int, input().split())

hour = h
min = m - 45

# 시간이 바뀔 때
if min < 0:
  min = 60 + min
  hour = hour -1
  # 바뀐 시간이 23시 일 때
  if hour == -1:
    hour = 23

print(hour, min)

h, m = map(int, input().split())
time = int(input().strip())

hour = h
min = m + time

if min > 59:
  plus_hour = min // 60
  hour += plus_hour
  min = min % 60
  if hour > 23:
    hour = hour - 24

print(hour, min)

a,b,c = map(int, input().split())

if (a==b and b==c):
  print(10000 + a * 1000)
elif (a==b):
  print(1000 + a * 100)
elif (a==c):
  print(1000 + a * 100)
elif (b==c):
  print(1000 + c * 100)
else:
  print(max(a,b,c) * 100)

a = int(input().strip())
b = int(input().strip())

if (a>0):
  if (b>0):
    print(1)
  elif (b<0):
    print(4)
elif (a<0):
  if (b>0):
    print(2)
  elif (b<0):
    print(3)

year = int(input().strip())
a = (year % 4 == 0) and (year % 100 != 0)
b = (year % 400 == 0)
if a or b:
  print(1)
else:
  print(0)

score = int(input().strip())

if score>=90:
  print('A')
elif score>=80:
  print('B')
elif score>=70:
  print('C')
elif score>=60:
  print('D')
else:
  print('F')

n = int(input().strip())
arr = list(map(int, input().split()))

x = int(input().strip())

cnt = 0
for i in range(n-1):
  for j in range(i+1, n):
    sum = arr[i] + arr[j]
    if sum==x:
      cnt += 1

print(cnt)

n = int(input().strip())
arr = list(map(int, input().split()))
x = int(input().strip())

cnt = 0
arr.sort()

start = 0
end = n-1

while start < end:
  if (arr[start] + arr[end] == x):
    cnt += 1
    start += 1
  elif (arr[start] + arr[end] < x):
    start += 1
  elif (arr[start] + arr[end] > x):
    end -= 1

print(cnt)

n = int(input())
sum = 0
for i in range(n):
  sum += (i+1)
print(sum)

x = int(input())
n = int(input())
receipt = [list(map(int, input().split()))for _ in range(n)]

receipt

sum = 0
for i in range(n):
  sum += (receipt[i][0] * receipt[i][1])

if sum==x:
  print("Yes")
else:
  print("No")



import sys

t = int(sys.stdin.readline())
for i in range(t):
  a, b = map(int, sys.stdin.readline().split())
  print(a+b)

n = int(input())

for i in range(n):
  print(' ' * (n-1-i) + '*' * (i+1))

print('a'+'b')
print('a', 'b')

n = int(input())
score = list(map(int, input().split()))
max_score = max(score)

sum = 0
for i in range(n):
  temp = score[i]/max_score * 100
  print(temp)
  sum += temp
print(sum / n)

205 / 3

