# -*- coding: utf-8 -*-
"""sort_array1_string

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tlxXsSCGOBA-jN9K8WsOgEJzKoPhKI-d
"""

# 2587
n = int(input())

arr = [int(input()) for _ in range(n)]


for i in range(n-1):
  min = arr[i]
  for j in range(i+1, n):
      if min > arr[j]:
        min = arr[j]
        arr[i], arr[j] = arr[j], arr[i]

for x in arr:
  print(x)

import sys
arr = [int(input()) for _ in range(5)]

avg = int(sum(arr) / len(arr))
mid = sorted(arr)[2]

print(avg)
print(mid)

n, k = map(int, input().split())
score = list(map(int, input().split()))
score.sort(reverse = True)

print(score[k-1])

import sys
n = int(sys.stdin.readline())
arr = [int(sys.stdin.readline()) for _ in range(n)]

arr.sort()

for x in arr:
  print(x)

n = input()
arr = [int(x) for x in n]
arr.sort(reverse = True)
for x in arr:
  print(x, end = '')

n = int(input())
coords = [list(map(int, input().split())) for _ in range(n)]
coords.sort(key = lambda x : (x[0], x[1]))

for x in coords:
  print(x[0], x[1])

coords

n = int(input())
coords = [list(map(int, input().split())) for _ in range(n)]

coords.sort(key = lambda x : (x[1], x[0]))

for x in coords:
  print(x[0], x[1])

for x in coords:
  print(x[0], x[1])

# 10814 나이순 정
n = int(input())
memb = [list(input().split()) for _ in range(n)]

memb.sort(key = lambda x : int(x[0]))

for x in memb:
  print(x[0], x[1])

n = int(input())

for i in range(n):
    print('*' * i)

n = int(input())

for i in range(n):
  a, b = map(int, input().split())
  print(f"Case #{i+1}:", a+b)

n = int(input())
div = n // 4
for i in range(div):
  print('long ', end = '')
print('int')

n = int(input())
for i in range(1, 10):
  print(f'{n} * {i} = {i * n}')

n = int(input())

for i in range(n):
  a,b = map(int, input().split())
  print(a+b)

n, m = map(int, input().split())
basket = [(i+1) for i in range(n)]

for i in range(m):
  a,b = map(int, input().split())
  basket[a-1], basket[b-1] = basket[b-1], basket[a-1]

print(*basket)

students = [0]* 30

for i in range(28):
  student = int(input())
  students[student-1] += 1

for i in range(30):
  if students[i] == 0:
    print(i + 1)

n = int(input())
arr = list(map(int, input().split()))
v = int(input())
cnt = 0
for i in arr:
  if i == v:
    cnt+=1
print(cnt)

n, x = map(int, input().split())
arr = list(map(int, input().split()))

for i in arr:
  if i < x:
    print(i, end = ' ')

#  10810
n, m = map(int, input().split())
basket = [0]*n  # 들어가는 공의 번호 : 0 0 0 0 0
put_ball = [list(map(int, input().split())) for _ in range(m)] # 1 2 3 4 5

for put in put_ball:
  start = put[0]-1
  end = put[1]-1
  basket[start:end+1] = [put[2]] * (end - start + 1)

print(*basket)

#  10810 수
n, m = map(int, input().split())
basket = [0]*n  # 들어가는 공의 번호 : 0 0 0 0 0

for i in range(m):
  start, end, put = map(int, input().split())
  basket[start-1:end] = [put] * (end - start + 1)

print(*basket)

s = input()
i = int(input())
print(s[i-1])

n = int(input())
for i in range(n):
    word = input()
    print(word[0]+word[-1])

while True:
  try:
    a = input()
    print(a)
  except:
    break

word = input()
chars = ['ABC', 'DEF', 'GHI', 'JKL', 'MNO', 'PQRS', 'TUV', 'WXYZ']
sum = 0
for w in word:
  for i in range(8):
    if w in chars[i]:
      sum += (i+1 +2)
      break
print(sum)

chro = ['c=', 'c-', 'dz=', 'd-', 'lj', 'nj', 's=', 'z=']
word = input()

for i in chro:
  if i in word:
    word = word.replace(i, '1')
print(len(word))

print('         ,r\'"7')
print('r`-_   ,\'  ,/')
print(' \\. ". L_r\'')
print('   `~\\/')
print('      |')
print('      |')

contents = [1,1,2,2,2,8]
lst = list(map(int, input().split()))

for i in range(6):
  print(contents[i] - lst[i], end = ' ')

n = int(input())

for i in range(2*n-1):
  if i< n:
    print(' ' * ((n-1)-i) + '*' * (2*i + 1))
  else:
    i = 2 * (n-1) - i
    print(' ' * ((n-1)-i) + '*' * (2*i + 1))

word = input()

is_pal = 1
for i in range(len(word)//2):
  if (word[i] != word[len(word)-i-1]):
    is_pal = 0
    break

if is_pal == 0:
  print(0)
else:
  print(1)

n = int(input())
words = [input() for _ in range(n)]

cnt = 0
for word in words:
  alpha = []
  is_group = 1
  for idx, w in enumerate(word):
    if w not in alpha:
      alpha.append(w)
    elif w in alpha and w != word[idx-1]:
      is_group = 0
      break

  if is_group:
    cnt+=1
print(cnt)

n = int(input())
cnt = 0

for _ in range(n):
  alpha = set()
  prev = None
  is_group = 1

  for w in input():
    if w != prev:
      if w in alpha:
        is_group = 0
        break
      alpha.add(w)
      prev = w

  if is_group: cnt+=1
print(cnt)

n = int(input())
lst = [0]*(10001)
for i in range(n):
  lst[int(input())] += 1
for i in range(len(n)):
  if i != 0:
    for j in range(lst[i]):
      print(i)

# 2738
n, m = map(int, input().split())
a = [list(map(int, input().split())) for _ in range(n)]
b = [list(map(int, input().split())) for _ in range(n)]

for i in range(n):
  for j in range(m):
    print(a[i][j] + b[i][j], end = ' ')
  print("")

